#!/bin/bash

# This script downloads the standard closed-source Stage 2 and Stage 3 bootloaders 
# required to boot a Raspberry Pi. 
# They are loaded by the SoC's ROM before our kernel.img is executed.

echo "Downloading standard GPU bootloader files for Raspberry Pi 1 B..."

wget -q --show-progress https://github.com/raspberrypi/firmware/raw/master/boot/bootcode.bin -O bootcode.bin
wget -q --show-progress https://github.com/raspberrypi/firmware/raw/master/boot/start.elf -O start.elf

echo ""
echo "Boot files downloaded successfully!"
echo "---------------------------------------------------------"
echo "Instructions to run your bare metal kernel:"
echo "1. Format an SD card as FAT32."
echo "2. Copy the following files to the root directory of the SD card:"
echo "   - bootcode.bin"
echo "   - start.elf"
echo "   - kernel.img (generated by running 'make')"
echo "3. Insert the SD card into your Raspberry Pi 1 B and power it on."
echo "---------------------------------------------------------"
